default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: furima_42318_development

test:
  <<: *default
  database: furima_42318_test

production:
  <<: *default
  database: furima_42318_production
  username: furima_42318
  password: <%= ENV["FURIMA_42318_DATABASE_PASSWORD"] %>
